---
- name: Update package cache
  package:
    update_cache: yes
  when: not (cosmos_skip_docker_install | default(false))

- name: Install required packages
  package:
    name:
      - docker.io
      - docker-compose
      - git
      - curl
    state: present
  when: not (cosmos_skip_docker_install | default(false))

- name: Start and enable Docker
  systemd:
    name: docker
    state: started
    enabled: yes
  when: not (cosmos_skip_docker_install | default(false))

- name: Create cosmos user
  user:
    name: "{{ cosmos_user }}"
    home: "{{ cosmos_home }}"
    shell: /bin/bash
    create_home: yes
    system: no
  when: cosmos_user != ansible_user

- name: Add cosmos user to docker group
  user:
    name: "{{ cosmos_user }}"
    groups: docker
    append: yes
  when: not (cosmos_skip_docker_install | default(false)) and cosmos_user != ansible_user

- name: Create cosmos directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ cosmos_user }}"
    group: "{{ cosmos_user }}"
    mode: '0755'
  loop:
    - "{{ cosmos_home }}"
    - "{{ cosmos_home }}/logs"
    - "{{ cosmos_home }}/data"