---
# Development environment specific variables

cosmos_environment: dev

# Development-specific settings
cosmos_registry: docker.io
cosmos_namespace: openc3inc
cosmos_tag: "6.4.2"

# Enable development features
cosmos_log_level: debug
cosmos_local_mode: true
cosmos_demo: true
cosmos_deployment_method: file_copy