apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cosmos-redis-pvc
  namespace: cosmos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cosmos-redis-ephemeral-pvc
  namespace: cosmos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cosmos-bucket-pvc
  namespace: cosmos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cosmos-gems-pvc
  namespace: cosmos
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi