---
# Localhost testing environment

cosmos_environment: dev
cosmos_user: codespace
cosmos_home: /workspaces/cosmos-project/test-deployment
cosmos_repo: file:///workspaces/cosmos-project

# Test with current settings
cosmos_tag: "6.4.2"
cosmos_registry: docker.io
cosmos_namespace: openc3inc

# Skip Docker installation for testing (no sudo required)
cosmos_skip_docker_install: true
cosmos_deployment_method: file_copy